### ISSUE TITLE
Workflow not working with custom model objects

### ISSUE THREAD

**Issue by spark-green** [symbiote/silverstripe-advancedworkflow#297]
Has anyone tried extending advancedworkflow to custom model objects ?
I tried to extend mycustomobject as per given in the documentation _as below_, model and controller class successfully extends workflow, but problem is, approve/rejects actions are not working. When user clicks on  Workflow options > Accept / Reject, it doesnot reflect any action or changes

_In order to apply workflow to other classes (e.g. `MyObject`), you need to apply it to both the model class and the controller which is used for editing it. Here's an example for `MyObject` which is managed through a `MyObjectAdmin` controller, extending from `ModelAdmin`. 
`mysite/_config/config.yml`:

```yaml
MyObject:
  extensions:
    - WorkflowApplicable
MyObjectAdmin:
  extensions:
    - AdvancedWorkflowExtension_
```

Am I missing any settings in config file or custom model class? Any help on this is much appreciated.
