### ISSUE TITLE
...references nonexistent WorkflowApplicable in 'extensions'

### ISSUE THREAD

**Issue by TimDKDK** [symbiote/silverstripe-advancedworkflow#417]
using SS 4.5.1, when adding the following to my yml,

HouseLand:
    extensions:
        - WorkflowApplicable
HouseLandAdmin:
    extensions:
        - AdvancedWorkflowExtension

I get the following error:

Uncaught InvalidArgumentException: HouseLand references nonexistent WorkflowApplicable in 'extensions'

**Comment by robbieaverill** [comment]
Hi @TimDKDK, the namespaces for the extensions are wrong. Try this:

```yaml
HouseLand:
  extensions:
    - Symbiote\AdvancedWorkflow\Extensions\WorkflowApplicable
HouseLandAdmin:
  extensions:
    - Symbiote\AdvancedWorkflow\Extensions\AdvancedWorkflowExtension
```
